package wshotel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-05-28T14:11:26.327+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "HotelCRUDService", 
                  wsdlLocation = "http://desktop-28rsbap:8080/reservation.hotel.ws.ejb/HotelCRUD?wsdl",
                  targetNamespace = "http://ws/") 
public class HotelCRUDService extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws/", "HotelCRUDService");
    public final static QName HotelCRUDPort = new QName("http://ws/", "HotelCRUDPort");
    static {
        URL url = null;
        try {
            url = new URL("http://desktop-28rsbap:8080/reservation.hotel.ws.ejb/HotelCRUD?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HotelCRUDService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://desktop-28rsbap:8080/reservation.hotel.ws.ejb/HotelCRUD?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HotelCRUDService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelCRUDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelCRUDService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HotelCRUDService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HotelCRUDService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HotelCRUDService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HotelCRUD
     */
    @WebEndpoint(name = "HotelCRUDPort")
    public HotelCRUD getHotelCRUDPort() {
        return super.getPort(HotelCRUDPort, HotelCRUD.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelCRUD
     */
    @WebEndpoint(name = "HotelCRUDPort")
    public HotelCRUD getHotelCRUDPort(WebServiceFeature... features) {
        return super.getPort(HotelCRUDPort, HotelCRUD.class, features);
    }

}
