package wshotel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-05-28T14:11:26.244+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://ws/", name = "HotelCRUD")
@XmlSeeAlso({ObjectFactory.class})
public interface HotelCRUD {

    @WebMethod
    @RequestWrapper(localName = "updateHotel", targetNamespace = "http://ws/", className = "wshotel.UpdateHotel")
    @ResponseWrapper(localName = "updateHotelResponse", targetNamespace = "http://ws/", className = "wshotel.UpdateHotelResponse")
    public void updateHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "getHotels", targetNamespace = "http://ws/", className = "wshotel.GetHotels")
    @ResponseWrapper(localName = "getHotelsResponse", targetNamespace = "http://ws/", className = "wshotel.GetHotelsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotel.Hotel> getHotels();

    @WebMethod
    @RequestWrapper(localName = "deleteHotel", targetNamespace = "http://ws/", className = "wshotel.DeleteHotel")
    @ResponseWrapper(localName = "deleteHotelResponse", targetNamespace = "http://ws/", className = "wshotel.DeleteHotelResponse")
    public void deleteHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getHotel", targetNamespace = "http://ws/", className = "wshotel.GetHotel")
    @ResponseWrapper(localName = "getHotelResponse", targetNamespace = "http://ws/", className = "wshotel.GetHotelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public wshotel.Hotel getHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "createHotel", targetNamespace = "http://ws/", className = "wshotel.CreateHotel")
    @ResponseWrapper(localName = "createHotelResponse", targetNamespace = "http://ws/", className = "wshotel.CreateHotelResponse")
    public void createHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
