package wshotelmetier;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2018-06-01T21:12:24.794+02:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://ws/", name = "HotelMetierImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface HotelMetierImpl {

    @WebMethod
    @RequestWrapper(localName = "commenterHoter", targetNamespace = "http://ws/", className = "wshotelmetier.CommenterHoter")
    @ResponseWrapper(localName = "commenterHoterResponse", targetNamespace = "http://ws/", className = "wshotelmetier.CommenterHoterResponse")
    public void commenterHoter(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3
    );

    @WebMethod
    @RequestWrapper(localName = "consulterChambresParAdresse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParAdresse")
    @ResponseWrapper(localName = "consulterChambresParAdresseResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParAdresseResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotelmetier.Chambre> consulterChambresParAdresse(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "reservationChambre", targetNamespace = "http://ws/", className = "wshotelmetier.ReservationChambre")
    @ResponseWrapper(localName = "reservationChambreResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ReservationChambreResponse")
    public void reservationChambre(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        wshotelmetier.Date arg2
    );

    @WebMethod
    @RequestWrapper(localName = "consulterChambresParVilleOuParCodeDepartement", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParVilleOuParCodeDepartement")
    @ResponseWrapper(localName = "consulterChambresParVilleOuParCodeDepartementResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParVilleOuParCodeDepartementResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotelmetier.Chambre> consulterChambresParVilleOuParCodeDepartement(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "consulterProfils", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterProfils")
    @ResponseWrapper(localName = "consulterProfilsResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterProfilsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotelmetier.Profil> consulterProfils();

    @WebMethod
    @RequestWrapper(localName = "consulterChambresParCriteres", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParCriteres")
    @ResponseWrapper(localName = "consulterChambresParCriteresResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParCriteresResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotelmetier.Chambre> consulterChambresParCriteres(
        @WebParam(name = "arg0", targetNamespace = "")
        wshotelmetier.ConsulterChambresParCriteres.Arg0 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "consulterChambresParIntervallePrix", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParIntervallePrix")
    @ResponseWrapper(localName = "consulterChambresParIntervallePrixResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParIntervallePrixResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotelmetier.Chambre> consulterChambresParIntervallePrix(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "consulterHotelsRegion", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterHotelsRegion")
    @ResponseWrapper(localName = "consulterHotelsRegionResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterHotelsRegionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotelmetier.Hotel> consulterHotelsRegion();

    @WebMethod
    @RequestWrapper(localName = "consulterChambresEnchere", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresEnchere")
    @ResponseWrapper(localName = "consulterChambresEnchereResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresEnchereResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotelmetier.Chambre> consulterChambresEnchere();

    @WebMethod
    @RequestWrapper(localName = "annulerReservation", targetNamespace = "http://ws/", className = "wshotelmetier.AnnulerReservation")
    @ResponseWrapper(localName = "annulerReservationResponse", targetNamespace = "http://ws/", className = "wshotelmetier.AnnulerReservationResponse")
    public void annulerReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "authentificationParProfil", targetNamespace = "http://ws/", className = "wshotelmetier.AuthentificationParProfil")
    @ResponseWrapper(localName = "authentificationParProfilResponse", targetNamespace = "http://ws/", className = "wshotelmetier.AuthentificationParProfilResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Object authentificationParProfil(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "consulterChambresHotel", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresHotel")
    @ResponseWrapper(localName = "consulterChambresHotelResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresHotelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotelmetier.Chambre> consulterChambresHotel(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "supprimerCompteUtilisateur", targetNamespace = "http://ws/", className = "wshotelmetier.SupprimerCompteUtilisateur")
    @ResponseWrapper(localName = "supprimerCompteUtilisateurResponse", targetNamespace = "http://ws/", className = "wshotelmetier.SupprimerCompteUtilisateurResponse")
    public void supprimerCompteUtilisateur(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "consulterChambresParServices", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParServices")
    @ResponseWrapper(localName = "consulterChambresParServicesResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ConsulterChambresParServicesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<wshotelmetier.Chambre> consulterChambresParServices(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0
    );

    @WebMethod
    @RequestWrapper(localName = "clientParticipeAuxEnchere", targetNamespace = "http://ws/", className = "wshotelmetier.ClientParticipeAuxEnchere")
    @ResponseWrapper(localName = "clientParticipeAuxEnchereResponse", targetNamespace = "http://ws/", className = "wshotelmetier.ClientParticipeAuxEnchereResponse")
    public void clientParticipeAuxEnchere(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.Double arg2
    );

    @WebMethod
    @RequestWrapper(localName = "ajouterUtilisateur", targetNamespace = "http://ws/", className = "wshotelmetier.AjouterUtilisateur")
    @ResponseWrapper(localName = "ajouterUtilisateurResponse", targetNamespace = "http://ws/", className = "wshotelmetier.AjouterUtilisateurResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.Object ajouterUtilisateur(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.lang.String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.lang.String arg8
    );
}
